// LeadGen Section preview — §9.2 (E5) sim parameterization support.
//
// Two responsibilities, both PURE (no DB, no I/O):
//   1. parsePreviewSim — the typed parse of the §9.2 `sim` request block
//      ({ state, answers, auto_advance, flow }).
//   2. applyPreviewSimMarkup — server-renders a sim state INTO the preset
//      markup so the Studio iframe shows the REAL runtime state (selected
//      classes, error markup, success markup) instead of the deleted
//      outer-iframe attribute hacks (09 §9.2: "All sims are SERVER-rendered
//      into the srcdoc").
//
// WHY A POST-RENDER TRANSFORM (documented choice, 09 §9.1): the shared preset
// renderer (components/presets.ts) is byte-frozen for the live /lg shell —
// its render signatures may not grow sim parameters. The presets cannot
// express selected/error state, so the sim pass rewrites the RENDERED string.
// This is safe because the markup is fully machine-generated by presets.ts:
// every attribute is double-quoted and every author value is escapeHtml-
// escaped (`<>&"` never appear raw inside attributes or text), so `<` / `>`
// are structural — a small balanced-tag scanner is exact, not heuristic.
//
// RUNTIME PARITY (read-only mirrors of src/public/leadgen/runtime/*):
//   selected   → runtime/render.ts applySelectionClasses: SELECTED_CLASS
//                ("lg-selected") + aria-checked="true" on the matching
//                [data-lg-choice], aria-checked="false" on all other choices.
//                NOTE: markSelectionInSlice is NOT a pure mirror — it
//                additionally special-cases <option> tags (toggling native
//                `selected`) to approximate native <select> display semantics,
//                which the runtime function never does. A dropdown's matching
//                <option> gains `selected` (placeholder loses it).
//   error      → runtime/render.ts setFieldError: the [data-lg-field] block
//                gains ERROR_CLASS ("lg-error"), its [data-lg-input] gains
//                aria-invalid="true", and the [data-lg-error-for] slot shows
//                the message — SHOWN, i.e. the `hidden` attribute presets.ts
//                autoErrorSlot renders it with is REMOVED (render.ts:243
//                toggleHidden), which upsertErrorMessage below now mirrors.
//                When the author placed no ValidationError slot, a slot in
//                renderValidationError's exact shape is injected after the
//                question block so the message is VISIBLE.
//   validation_success → the `.lg-valid` chrome convention (designs/
//                default-funnel/styles.ts colors it validation.successColor).
//   Message copy mirrors runtime/validation.ts verbatim.

import { escapeHtml } from "../../editor/sanitize";
import { COMPONENT_CATALOG } from "../../public/leadgen/components/registry";
import type { ComponentType } from "../../public/leadgen/components/registry";
import { flattenComponents } from "../../public/leadgen/components/content-schema";
import type { LeadgenComponentNode } from "../../public/leadgen/components/content-schema";
import type { DefaultFunnelDesign } from "../../public/leadgen/designs/default-funnel/tokens";

// ---------------------------------------------------------------------------
// §9.2 sim request block — typed parse
// ---------------------------------------------------------------------------

export const LEADGEN_PREVIEW_SIM_STATES = [
  "default",
  "selected",
  "error",
  "dependency",
  "validation_success",
  "validation_error",
] as const;

export type LeadgenPreviewSimState = (typeof LEADGEN_PREVIEW_SIM_STATES)[number];

export interface LeadgenPreviewSimRequest {
  state: LeadgenPreviewSimState;
  // null = the caller sent no answers object (distinct from an empty {} —
  // an empty object still opts into the answers-driven dependency basis,
  // matching the legacy `sample_answers: {}` behavior).
  answers: Record<string, unknown> | null;
  // §9.2 flow simulation: the answer sequence reduced later-entries-win into
  // an accumulated record by the handler.
  flow: Array<{ internal_field: string; value: unknown }>;
  // Accepted per the §9.2 body shape; a static server render cannot express
  // auto-advance (it is a BEHAVIOR) — it becomes live with the §9.1 runtime-
  // bundle-in-iframe leg (Slice D).
  auto_advance: boolean;
}

const DEFAULT_SIM: LeadgenPreviewSimRequest = {
  state: "default",
  answers: null,
  flow: [],
  auto_advance: false,
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

// Parse the request's `sim` block. Absent → the default sim. Any shape
// violation → a { field: message } error record for the handler's 400.
export function parsePreviewSim(
  raw: unknown,
): { sim: LeadgenPreviewSimRequest; error: Record<string, string> | null } {
  if (raw === undefined || raw === null) return { sim: DEFAULT_SIM, error: null };
  if (!isRecord(raw)) {
    return { sim: DEFAULT_SIM, error: { sim: "sim must be an object" } };
  }
  const out: LeadgenPreviewSimRequest = { ...DEFAULT_SIM, flow: [] };

  const state = raw["state"];
  if (state !== undefined && state !== null) {
    if (
      typeof state !== "string" ||
      !(LEADGEN_PREVIEW_SIM_STATES as readonly string[]).includes(state)
    ) {
      return {
        sim: DEFAULT_SIM,
        error: { "sim.state": `sim.state must be one of ${LEADGEN_PREVIEW_SIM_STATES.join("|")}` },
      };
    }
    out.state = state as LeadgenPreviewSimState;
  }

  const answers = raw["answers"];
  if (answers !== undefined && answers !== null) {
    if (!isRecord(answers)) {
      return { sim: DEFAULT_SIM, error: { "sim.answers": "sim.answers must be an object" } };
    }
    out.answers = answers;
  }

  const flow = raw["flow"];
  if (flow !== undefined && flow !== null) {
    if (!Array.isArray(flow)) {
      return { sim: DEFAULT_SIM, error: { "sim.flow": "sim.flow must be an array" } };
    }
    for (const step of flow) {
      // Defensive skip (the §12.11 cleanObject-drop discipline): a malformed
      // step contributes nothing rather than failing the whole preview.
      if (!isRecord(step)) continue;
      const field = step["internal_field"];
      if (typeof field !== "string" || field === "") continue;
      out.flow.push({ internal_field: field, value: step["value"] });
    }
  }

  out.auto_advance = raw["auto_advance"] === true;
  return { sim: out, error: null };
}

// ---------------------------------------------------------------------------
// answered predicate — runtime/dependencies.ts isAnswered mirror (read-only)
// ---------------------------------------------------------------------------

export function isAnsweredValue(value: unknown): boolean {
  if (value === undefined || value === null) return false;
  if (typeof value === "string") return value.trim() !== "";
  if (Array.isArray(value)) return value.length > 0;
  if (typeof value === "object") return Object.keys(value as object).length > 0;
  return true;
}

// ---------------------------------------------------------------------------
// machine-generated-markup helpers (exact over presets.ts output — see header)
// ---------------------------------------------------------------------------

// Elements presets.ts emits without a closing tag.
const VOID_TAGS = new Set(["input", "img", "br", "hr", "meta", "link", "source", "wbr"]);

interface Span {
  start: number;
  end: number;
}

// The [start, end) span of the element whose OPENING TAG contains `token`
// (an `attr="value"` string). Balanced-tag scan from the opening tag; null
// when the token is absent (e.g. the component was dependency-filtered out).
function elementSpan(html: string, token: string): Span | null {
  const at = html.indexOf(token);
  if (at === -1) return null;
  const start = html.lastIndexOf("<", at);
  if (start === -1) return null;
  let first = true;
  let depth = 0;
  for (const m of html.slice(start).matchAll(/<(\/?)([a-zA-Z][a-zA-Z0-9-]*)[^>]*?>/g)) {
    const end = start + (m.index ?? 0) + m[0].length;
    const isClose = m[1] === "/";
    const name = (m[2] ?? "").toLowerCase();
    const isVoid = !isClose && (VOID_TAGS.has(name) || m[0].endsWith("/>"));
    if (first) {
      if (isClose) return null; // defensive: token cannot sit in a close tag
      if (isVoid) return { start, end };
      depth = 1;
      first = false;
      continue;
    }
    if (isVoid) continue;
    depth += isClose ? -1 : 1;
    if (depth === 0) return { start, end };
  }
  return null; // defensive: unbalanced markup — leave the html untouched
}

// Append/extend the class attribute on ONE opening-tag string.
function addClassToTag(tag: string, cls: string): string {
  const m = tag.match(/\bclass="([^"]*)"/);
  if (m === null) return `${tag.slice(0, tag.length - 1)} class="${cls}">`;
  if (m[1] !== undefined && m[1].split(" ").indexOf(cls) !== -1) return tag;
  return tag.replace(m[0], `class="${m[1]} ${cls}"`);
}

// Set (replace-or-append) a double-quoted attribute on ONE opening-tag string.
// `name` is always a fixed literal (aria-*), never author data.
function setTagAttr(tag: string, name: string, value: string): string {
  const re = new RegExp(`\\b${name}="[^"]*"`);
  if (re.test(tag)) return tag.replace(re, `${name}="${value}"`);
  return `${tag.slice(0, tag.length - 1)} ${name}="${value}">`;
}

// Drop a BOOLEAN attribute (fixed literal, never author data) from ONE
// opening-tag string. Quoted attribute VALUES are masked out first so a
// `name` token sitting inside an author value (a placeholder, a style, an
// internal_field) can never be mistaken for the attribute itself — the same
// "every attribute is double-quoted" property the header relies on.
function dropBooleanTagAttr(tag: string, name: string): string {
  const masked = tag.replace(/"[^"]*"/g, (q) => " ".repeat(q.length));
  const hit = masked.match(new RegExp(`\\s${name}(?=[\\s>/])`));
  if (hit === null || hit.index === undefined) return tag;
  return tag.slice(0, hit.index) + tag.slice(hit.index + hit[0].length);
}

// ---------------------------------------------------------------------------
// per-question slice transforms
// ---------------------------------------------------------------------------

// Selected-state markup over one question element's slice. `values` are the
// String() forms of the answered value (multi-select = every member —
// applySelectionClasses semantics).
function markSelectionInSlice(slice: string, values: readonly string[]): string {
  const escaped = values.map((v) => escapeHtml(v));
  let selectedAnOption = false;
  let out = slice.replace(/<(button|option)\b[^>]*?>/g, (tag, tagName: string) => {
    const choice = tag.match(/\bdata-lg-choice="([^"]*)"/);
    if (choice === null) return tag; // e.g. the B9 Other trigger — never a value
    const isOn = escaped.indexOf(choice[1] ?? "") !== -1;
    if (tagName === "option") {
      // §9.2: dropdowns select the REAL option; the disabled placeholder
      // loses its `selected` below so exactly one option is selected.
      if (!isOn) return tag;
      selectedAnOption = true;
      return `${tag.slice(0, tag.length - 1)} selected>`;
    }
    // applySelectionClasses mirror (P5 tail — kept in lockstep with the P5
    // S5c ADJ-R8 runtime fix): aria-checked true/false on EVERY choice of
    // the answered question, matching the SSR aria-checked="false" default
    // this is layered over; class also added on the match.
    let next = setTagAttr(tag, "aria-checked", isOn ? "true" : "false");
    if (isOn) {
      next = addClassToTag(next, "lg-selected");
      next = setTagAttr(next, "aria-checked", "true");
    }
    return next;
  });
  if (selectedAnOption) {
    out = out.replace('<option value="" disabled selected>', '<option value="" disabled>');
  }
  return out;
}

// Error-state markup over one question element's slice (setFieldError mirror):
// ERROR_CLASS on the field block (the hydration root) + aria-invalid on its
// data-lg-input inputs (the root itself may BE the input — renderTextInput
// hydrates the <input> directly).
function markErrorInSlice(slice: string): string {
  const rootEnd = slice.indexOf(">");
  if (rootEnd === -1) return slice;
  let root = slice.slice(0, rootEnd + 1);
  root = addClassToTag(root, "lg-error");
  if (/\bdata-lg-input\b/.test(root)) root = setTagAttr(root, "aria-invalid", "true");
  const rest = slice
    .slice(rootEnd + 1)
    .replace(/<(input|select|textarea)\b[^>]*?>/g, (tag) =>
      /\bdata-lg-input\b/.test(tag) ? setTagAttr(tag, "aria-invalid", "true") : tag,
    );
  return root + rest;
}

// Success-state markup: the `.lg-valid` chrome convention on the field block.
function markValidInSlice(slice: string): string {
  const rootEnd = slice.indexOf(">");
  if (rootEnd === -1) return slice;
  return addClassToTag(slice.slice(0, rootEnd + 1), "lg-valid") + slice.slice(rootEnd + 1);
}

// ---------------------------------------------------------------------------
// authored-address per-subfield rule — runtime/validation.ts mirror (read-only)
// ---------------------------------------------------------------------------

// validation.ts addressFieldKey: the answer key ONE authored address field spec
// records under — props.maps.fills.<kind> override, else `{base}_{kind}`, and a
// `full_address` spec records under the base itself. Base = internal_field ??
// question_id (validation.ts addressBase; presets.ts renderAddressFieldSet uses
// the same ladder for the data-lg-field it stamps on each subfield wrapper).
function addressFieldKey(node: LeadgenComponentNode, kind: string): string {
  const own = typeof node.internal_field === "string" ? node.internal_field.trim() : "";
  const base = own !== "" ? own : node.question_id;
  if (kind === "full_address") return base;
  const maps = (node.props ?? {})["maps"];
  const fills = isRecord(maps) ? maps["fills"] : undefined;
  const override = isRecord(fills) ? fills[kind] : undefined;
  return typeof override === "string" && override.trim() !== "" ? override.trim() : `${base}_${kind}`;
}

// Message copy — runtime/validation.ts verbatim (parity, never invented copy).
export const PREVIEW_REQUIRED_MESSAGE = "This field is required.";
export const PREVIEW_INVALID_MESSAGE = "The value has an invalid format.";

// validation.ts validateAddressField's FORMAT leg, read-only mirror: the
// message a present-but-bad value produces for ONE authored spec, or null when
// the spec carries no format rule at all (a rule-less spec can only ever fail
// `required` — the sim "error" path — so live can never show it a format
// failure, and neither may the canvas).
//   validation:"zip5"                → the zip5 copy, verbatim
//   validation:{regex,message}       → the AUTHOR'S message, else the generic
// (validateAddressField's third branch, "Enter at most 200 characters.", is
// keyed to the VALUE's length; a sim has no value, so the representative
// failure for a rule is its pattern failure.)
function addressFormatMessage(spec: Record<string, unknown>): string | null {
  const validation = spec["validation"];
  if (validation === "zip5") return "Enter a valid 5-digit ZIP code.";
  if (!isRecord(validation)) return null;
  const regex = validation["regex"];
  if (typeof regex !== "string" || regex === "") return null;
  const message = validation["message"];
  return typeof message === "string" && message !== "" ? message : PREVIEW_INVALID_MESSAGE;
}

// The authored per-field specs of an AddressAutocompleteQuestion, or null when
// the node is not one / authored none. The `Array.isArray(props.fields)` gate is
// verbatim the runtime's own (validation.ts:462) — it is what decides whether
// the visitor gets PER-SUBFIELD failures or the whole-group one.
function addressFieldSpecs(
  node: LeadgenComponentNode,
): Array<{ key: string; required: boolean; formatMessage: string | null }> | null {
  if (node.type !== "AddressAutocompleteQuestion") return null;
  const specs = (node.props ?? {})["fields"];
  if (!Array.isArray(specs)) return null;
  const out: Array<{ key: string; required: boolean; formatMessage: string | null }> = [];
  for (const spec of specs) {
    if (!isRecord(spec)) continue;
    const kind = spec["field"];
    if (typeof kind !== "string") continue;
    out.push({
      key: addressFieldKey(node, kind),
      required: spec["required"] === true,
      formatMessage: addressFormatMessage(spec),
    });
  }
  return out;
}

// Fill the field's authored [data-lg-error-for] slot (setFieldError textContent
// leg) or, when the author placed none, inject a slot in renderValidationError's
// exact shape immediately AFTER the question element so the message is VISIBLE.
function upsertErrorMessage(
  html: string,
  field: string,
  message: string,
  questionEnd: number,
  design: DefaultFunnelDesign,
): string {
  const slotToken = `data-lg-error-for="${escapeHtml(field)}"`;
  const slot = elementSpan(html, slotToken);
  if (slot !== null) {
    const openEnd = html.indexOf(">", slot.start) + 1;
    const closeStart = html.lastIndexOf("<", slot.end - 1);
    if (openEnd > 0 && closeStart >= openEnd) {
      // R2 P8-5 M-4 (ADJ-P8-22): presets.ts autoErrorSlot renders the slot
      // `hidden` and EMPTY; setFieldError's second leg (render.ts:243
      // `toggleHidden(slot, message !== null)`) removes that attribute when it
      // fills the text. This mirror only ever filled the text, so — driven on
      // the real preview route — the canvas returned the message inside a
      // still-`hidden` <p> while the live page's own <p> had no `hidden` at
      // all: the operator was shown an error state with no error sentence.
      // Dropping the attribute is the exact mirror of removeAttribute.
      const open = dropBooleanTagAttr(html.slice(slot.start, openEnd), "hidden");
      return html.slice(0, slot.start) + open + escapeHtml(message) + html.slice(closeStart);
    }
  }
  const injected =
    `<p class="lg-error" role="alert" aria-live="polite" ${slotToken}` +
    ` style="color:${design.validation.errorTextColor}">${escapeHtml(message)}</p>`;
  return html.slice(0, questionEnd) + injected + html.slice(questionEnd);
}

// ---------------------------------------------------------------------------
// the sim pass
// ---------------------------------------------------------------------------

export interface LeadgenPreviewSimMarkupOptions {
  state: LeadgenPreviewSimState;
  // Selection markup applies for state="selected" AND whenever a flow was
  // provided (§9.2: the flow record is the dependency+selected basis).
  markSelection: boolean;
  // NORMALIZED answers (answers.ts normalizeAnswers output), keyed by
  // internal_field — the same record the dependency evaluation consumed.
  answers: Readonly<Record<string, unknown>>;
  // Dependency-visible question ids (null = no dependency pass ran → all
  // rendered leaves are visible).
  visibleIds: ReadonlySet<string> | null;
  // Dependency-effective requiredness by question_id (null → static
  // node.required) — mirrors validateValue's requiredNow override.
  requiredNow: ReadonlyMap<string, boolean> | null;
}

interface SimLeaf {
  node: LeadgenComponentNode;
  questionId: string;
  field: string;
}

// Answer-producing leaves that actually rendered (data-lg-question markers).
function simLeaves(
  nodes: readonly LeadgenComponentNode[],
  visibleIds: ReadonlySet<string> | null,
): SimLeaf[] {
  const out: SimLeaf[] = [];
  for (const node of flattenComponents(nodes)) {
    if (typeof node !== "object" || node === null) continue;
    const typed = node as LeadgenComponentNode;
    const catalog = COMPONENT_CATALOG[typed.type as ComponentType];
    if (catalog === undefined || catalog.produces === null) continue;
    const questionId = typeof typed.question_id === "string" ? typed.question_id : "";
    if (questionId === "") continue;
    if (visibleIds !== null && !visibleIds.has(questionId)) continue;
    out.push({
      node: typed,
      questionId,
      field: typeof typed.internal_field === "string" ? typed.internal_field : "",
    });
  }
  return out;
}

// Apply the §9.2 sim state INTO rendered section markup. Pure string → string;
// `html` is the renderSectionComponents(/Visible) output for `nodes` under
// `design`. Unknown/unmatched components are skipped defensively (drafts are
// unvalidated — preview never throws on them).
export function applyPreviewSimMarkup(
  html: string,
  nodes: readonly LeadgenComponentNode[],
  design: DefaultFunnelDesign,
  opts: LeadgenPreviewSimMarkupOptions,
): string {
  const leaves = simLeaves(nodes, opts.visibleIds);
  const answered = leaves.filter((l) => l.field !== "" && isAnsweredValue(opts.answers[l.field]));

  let out = html;

  // 1. selection markup (selected state / flow basis) on answered questions.
  if (opts.markSelection) {
    for (const leaf of answered) {
      const span = elementSpan(out, `data-lg-question="${escapeHtml(leaf.questionId)}"`);
      if (span === null) continue;
      const value = opts.answers[leaf.field];
      const values = Array.isArray(value) ? value.map((v) => String(v)) : [String(value)];
      out =
        out.slice(0, span.start) +
        markSelectionInSlice(out.slice(span.start, span.end), values) +
        out.slice(span.end);
    }
  }

  // 2. error state: required-now-but-empty visible fields (validateValue's
  //    `required` + isAnswered legs) get the full setFieldError markup.
  if (opts.state === "error") {
    for (const leaf of leaves) {
      // R2 P8-5 G3b-3: an AUTHORED address (props.fields[]) validates PER
      // SUBFIELD live — validation.ts:460-472 loops the specs, keys each
      // failure to addressFieldKey(spec.field) and `continue`s past the
      // group. Driven on the live funnel page with an empty required-ZIP
      // address, the visitor got ONE marked input and the message in the
      // [data-lg-error-for="{base}_zip"] slot; this mirror was marking the
      // GROUP instead — all 4 inputs aria-invalid, `lg-error` on the fieldset,
      // the message in the group slot, and the ZIP slot the visitor actually
      // reads left empty and hidden. The canvas was showing an error state the
      // live page cannot produce, and hiding the one it does.
      const specs = addressFieldSpecs(leaf.node);
      if (specs !== null) {
        for (const spec of specs) {
          if (!spec.required || isAnsweredValue(opts.answers[spec.key])) continue;
          out = applyErrorToField(out, spec.key, PREVIEW_REQUIRED_MESSAGE, design);
        }
        continue;
      }
      if (leaf.field === "") continue;
      const requiredNow = opts.requiredNow?.get(leaf.questionId) ?? leaf.node.required === true;
      if (!requiredNow || isAnsweredValue(opts.answers[leaf.field])) continue;
      out = applyErrorToLeaf(out, leaf, PREVIEW_REQUIRED_MESSAGE, design);
    }
  }

  // 3. validation success/error: the ANSWERED fields; when the caller sent no
  //    answers at all, the state previews on EVERY visible field (the Studio's
  //    "show me the state" affordance — otherwise the button would no-op).
  if (opts.state === "validation_success" || opts.state === "validation_error") {
    const targets = answered.length > 0 ? answered : leaves.filter((l) => l.field !== "");
    for (const leaf of targets) {
      if (opts.state === "validation_success") {
        const span = elementSpan(out, `data-lg-question="${escapeHtml(leaf.questionId)}"`);
        if (span === null) continue;
        out =
          out.slice(0, span.start) +
          markValidInSlice(out.slice(span.start, span.end)) +
          out.slice(span.end);
      } else {
        // R2 P8-5 G3c: the validation_error twin of the G3b-3 required fix,
        // and MEASURED the same way (scripts/p8 drive-g3-canvas-live-error.mjs,
        // scenario address_validation — 5 of 7 parity rows disagreed before
        // this). An AUTHORED address (props.fields[]) format-fails PER SUBFIELD
        // live: validation.ts validateAddressField runs each spec's OWN rule
        // and keys the failure to addressFieldKey(spec.field), so the visitor
        // who typed "123" into the ZIP got the ZIP wrapper marked (1 of 4
        // inputs, lg-error on [data-lg-field="{base}_zip"]) and read the ZIP
        // spec's OWN authored sentence in the {base}_zip slot. This mirror was
        // instead lighting the whole GROUP — 4 of 4 inputs, lg-error on the
        // fieldset, and the generic "The value has an invalid format." in the
        // group slot that live leaves `hidden` and empty.
        const specs = addressFieldSpecs(leaf.node);
        if (specs !== null) {
          for (const spec of specs) {
            // No format rule ⇒ live has no format failure to show for this
            // subfield (its only failure mode is `required`). Nothing is drawn
            // rather than a state the visitor can never reach.
            if (spec.formatMessage === null) continue;
            out = applyErrorToField(out, spec.key, spec.formatMessage, design);
          }
          continue;
        }
        out = applyErrorToLeaf(out, leaf, PREVIEW_INVALID_MESSAGE, design);
      }
    }
  }

  return out;
}

// One SUBFIELD's error treatment — setFieldError's exact two targets when the
// runtime keys a failure to a sub-field: the [data-lg-field="{field}"] wrapper
// (presets.ts renderAddressFieldSet stamps one per authored spec) and that
// field's own message slot. Same body as applyErrorToLeaf, sliced by field
// instead of by question.
function applyErrorToField(
  html: string,
  field: string,
  message: string,
  design: DefaultFunnelDesign,
): string {
  const span = elementSpan(html, `data-lg-field="${escapeHtml(field)}"`);
  if (span === null) return html;
  const slice = markErrorInSlice(html.slice(span.start, span.end));
  const next = html.slice(0, span.start) + slice + html.slice(span.end);
  return upsertErrorMessage(next, field, message, span.start + slice.length, design);
}

// One leaf's full error treatment: slice markup + the visible message.
function applyErrorToLeaf(
  html: string,
  leaf: SimLeaf,
  message: string,
  design: DefaultFunnelDesign,
): string {
  const span = elementSpan(html, `data-lg-question="${escapeHtml(leaf.questionId)}"`);
  if (span === null) return html;
  const slice = markErrorInSlice(html.slice(span.start, span.end));
  const next = html.slice(0, span.start) + slice + html.slice(span.end);
  return upsertErrorMessage(next, leaf.field, message, span.start + slice.length, design);
}
