// Default Listicle layout — MEASURED Senior-Saving reference baseline (v1.2).
// Authoritative token contract. Do NOT replace with abstract theme language.
// Any field with status: "BLOCKER…" must be resolved from a scrolled screenshot /
// computed CSS (mobile capture, Disclosure interaction, lower-page) before Phase 6
// default-layout parity can be accepted. The ONLY per-host brand swap is the logo.

export const defaultListicleLayoutTokens = {
  id: "default",
  source: "senior-saving-reference",
  status: "measured-visible-page-plus-blockers",
  viewports: {
    capturedDesktop: {
      viewportWidth: "1014px",
      viewportHeight: "857px",
      renderedPageWidth: "1000px",
      scrollbarWidth: "14px",
    },
    mobile: {
      width: "390px",
      status: "BLOCKER: capture required before final acceptance",
    },
  },

  page: {
    backgroundColor: "#ffffff",
    textColor: "#2a2a2a",
    fontFamily: "Arial, Helvetica, sans-serif",
    shellWidth: "100%",
    shellMinHeight: "100vh",
  },

  articleContainer: {
    maxWidth: "968px",
    paddingXDesktop: "16px",
    paddingXMobile: "16px",
    marginLeft: "auto",
    marginRight: "auto",
  },

  header: {
    height: "64px",
    backgroundColor: "#ce2e35",
    borderBottomColor: "#f4d1d3",
    borderBottomWidth: "1px",
    paddingX: "20px",
    paddingY: "0px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    boxSizing: "border-box",
  },

  logoSlot: {
    widthDesktop: "226px",
    heightDesktop: "36px",
    objectFit: "contain",
    objectPosition: "left center",
    display: "block",
    measuredLeft: "20px",
    measuredTop: "15px",
    measuredVisualHeight: "35px",
    measuredVisualWidth: "226px",
  },

  disclosureTrigger: {
    position: "top-right-header",
    color: "#ffffff",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "13px",
    fontWeight: "400",
    lineHeight: "16px",
    textDecoration: "none",
    cursor: "pointer",
    rightOffset: "20px",
    measuredRightEdge: "~981px",
    measuredLeftEdge: "~924px",
    measuredTop: "~27px",
    measuredHeight: "~13px",
  },

  disclosureInteraction: {
    status: "BLOCKER",
    instruction:
      "Open the reference Disclosure and measure whether it is anchor navigation, modal, dropdown, accordion, or scroll-to-disclosure. Do not implement from assumptions.",
  },

  articleTopSpacing: {
    headerBottomY: "64px",
    h1FirstGlyphTopY: "94px",
    visualGap: "30px",
    paddingTopDesktop: "23px",
    paddingTopMobile: "22px",
  },

  articleHeadline: {
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "#2c2c2c",
    fontSizeDesktop: "38px",
    fontSizeMobile: "32px",
    fontWeight: "700",
    lineHeightDesktop: "48px",
    lineHeightMobile: "39px",
    letterSpacing: "-0.4px",
    textAlign: "center",
    maxWidth: "820px",
    marginTop: "0px",
    marginBottom: "19px",
    measuredLine1GlyphBox: "y=94-128",
    measuredLine2GlyphBox: "y=142-168",
    measuredLineTopToTop: "48px",
  },

  byline: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
    marginBottom: "16px",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "12px",
    lineHeight: "15px",
    fontWeight: "700",
    color: "#4b5360",
    avatarSize: "31px",
    avatarRadius: "999px",
    measuredAvatarX: "327-357px",
    measuredAvatarY: "196-226px",
    measuredTextX: "374-670px",
    measuredTextY: "203-217px",
  },

  heroImage: {
    width: "100%",
    measuredWidth: "967px",
    measuredHeight: "484px",
    measuredX: "16px",
    measuredY: "242px",
    aspectRatio: "2 / 1",
    objectFit: "cover",
    objectPosition: "center center",
    borderRadius: "5px",
    marginTop: "0px",
    marginBottom: "22px",
    display: "block",
  },

  bodyParagraph: {
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSizeDesktop: "20px",
    fontSizeMobile: "18px",
    lineHeightDesktop: "30px",
    lineHeightMobile: "27px",
    fontWeight: "400",
    color: "#2a2a2a",
    letterSpacing: "0px",
    marginTop: "0px",
    marginBottom: "15px",
    measuredX: "16px",
    measuredParagraphGap: "14-16px",
  },

  strongText: { fontWeight: "700", color: "#2a2a2a" },

  sectionWrapper: {
    marginTop: "32px",
    marginBottom: "28px",
    status: "BLOCKER: confirm exact lower-page spacing from scrolled screenshot/computed CSS",
  },

  sectionHeading: {
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSizeDesktop: "28px",
    fontSizeMobile: "24px",
    lineHeight: "34px",
    fontWeight: "700",
    color: "#2a2a2a",
    marginTop: "28px",
    marginBottom: "16px",
    textDecoration: "none",
    status: "BLOCKER: exact lower-page value must be measured from Section 1",
  },

  sectionImage: {
    width: "100%",
    aspectRatio: "2 / 1",
    objectFit: "cover",
    objectPosition: "center center",
    borderRadius: "5px",
    marginTop: "12px",
    marginBottom: "20px",
    display: "block",
    status: "BLOCKER: confirm whether lower section images share hero aspect ratio and radius",
  },

  inlineLink: {
    color: "#ce2e35",
    fontWeight: "700",
    textDecoration: "none",
    hoverColor: "#b9272e",
    hoverTextDecoration: "underline",
    status: "BLOCKER: confirm from visible inline links such as provider links",
  },

  choiceButton: {
    backgroundColor: "#ce2e35",
    color: "#ffffff",
    borderColor: "#ce2e35",
    hoverBackgroundColor: "#b9272e",
    activeBackgroundColor: "#a8232a",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "18px",
    fontWeight: "700",
    lineHeight: "24px",
    borderWidth: "0px",
    borderRadius: "6px",
    paddingY: "14px",
    paddingX: "18px",
    width: "100%",
    maxWidth: "720px",
    minHeight: "52px",
    marginTop: "8px",
    marginBottom: "8px",
    cursor: "pointer",
    status:
      "BLOCKER: exact lower-page CTA button visual styling must be measured from scrolled screenshot/computed CSS before implementation acceptance",
  },

  choiceButtonGroup: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
    marginTop: "16px",
    marginBottom: "20px",
  },

  textCta: {
    display: "block",
    color: "#ce2e35",
    fontSize: "20px",
    fontWeight: "700",
    lineHeight: "30px",
    textAlign: "left",
    textDecoration: "none",
    marginTop: "16px",
    marginBottom: "22px",
    status: "BLOCKER: exact text CTA style not visible in first screenshot",
  },

  listBlock: {
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "20px",
    lineHeight: "30px",
    color: "#2a2a2a",
    marginTop: "10px",
    marginBottom: "16px",
    itemMarginBottom: "8px",
    paddingLeft: "0px",
    listStyle: "none",
    checkmarkMarker: "✔️ ",
    checkmarkMarkerSize: "20px",
    bulletMarker: "• ",
    bulletMarkerColor: "#2a2a2a",
  },

  legalDisclosureBlock: {
    fontSize: "14px",
    lineHeight: "21px",
    color: "#4b4b4b",
    marginTop: "32px",
    marginBottom: "24px",
    fontWeight: "400",
    status: "BLOCKER: exact lower-page legal block style not visible in first screenshot",
  },

  footer: {
    backgroundColor: "#ffffff",
    borderTopColor: "transparent",
    borderTopWidth: "0px",
    paddingTop: "24px",
    paddingBottom: "32px",
    paddingX: "16px",
    footerLogoWidth: "180px",
    footerLogoHeight: "auto",
    footerLogoMarginBottom: "16px",
    linkColor: "#2a2a2a",
    linkFontSize: "14px",
    linkLineHeight: "22px",
    linkTextDecoration: "none",
    linkHoverTextDecoration: "underline",
    legalFontSize: "12px",
    legalLineHeight: "18px",
    legalColor: "#555555",
    legalMarginTop: "16px",
    copyrightFontSize: "12px",
    copyrightLineHeight: "18px",
    copyrightColor: "#555555",
    copyrightMarginTop: "16px",
    status: "BLOCKER: exact footer styling must be measured from page bottom before acceptance",
  },
} as const;

export type DefaultListicleLayoutTokens = typeof defaultListicleLayoutTokens;
