-- Migration 0024 (rescue-4 round-2 / PR-2b): raise the LIVE feature-image
-- generation prompt quality so provisioned article images are visually
-- DISTINCT from one another and read like real editorial photography, not
-- samey, over-literal, staged catalog/stock or AI clip-art.
--
-- The per-article feature image is generated by generateFeatureImage
-- (api/src/ai/generators/image.ts), which resolves the 'feature-image'
-- use-case preset via resolveCategoryPreset. The only is_system 'feature-image'
-- preset is the `system-feature-image` row seeded by migration 0020. This
-- migration UPDATEs that exact row in place: it rewrites the System + User
-- prompt templates (and the flat prompt_template) to the editorial-photo-
-- director, vary-the-treatment, natural-and-unposed authoring contract.
--
-- Idempotency: a single UPDATE keyed on the stable (slug='system-feature-image',
-- category='feature-image') identity migration 0020 created. Re-running it sets
-- the same text — no duplicate rows, no schema change. text_model / image_model
-- are left untouched (the LOCKED gpt-5.5 / gpt-image-2 ids from 0020). The
-- {{title}} / {{vertical}} / {{brand_name}} tokens are exactly the
-- ones generateFeatureImage passes to resolveCategoryPreset and the resolver
-- interpolates at generation time.

UPDATE prompt_presets
SET system_prompt_template = 'You are an editorial photo director for {{brand_name}}, a {{vertical}} publication. Each image must be visually distinct from the others and look like a real editorial photograph, never generic stock or AI clip-art.',
    user_prompt_template = 'Describe ONE specific, evocative editorial image for the article "{{title}}" in the {{vertical}} space. Capture a concrete real-world moment that conveys the article''s core idea, not a literal label of the title. Vary the treatment - choose ONE: a candid over-the-shoulder moment; a warm close-up detail; a wide environmental scene; a hands-at-work top-down; or a natural portrait with the subject looking straight at the camera. If a person faces away or is mid-action, keep it natural and unposed, never staged or acting. Use natural directional light, shallow depth of field, real textures, and a calm modern palette. A soft illustrative or gentle cartoon style is allowed when it genuinely suits the subject. No text, no words, no logos, no watermarks, no collage. 16:9 landscape.',
    prompt_template = 'Describe ONE specific, evocative editorial image for the article {{title}} in the {{vertical}} space for {{brand_name}}, capturing a concrete real-world moment rather than a literal label of the title.'
WHERE slug = 'system-feature-image' AND category = 'feature-image';
