-- Migration 0025 (rescue-4 round-2 / PR-3, issue 16): replace the stub-like
-- legal-template bodies seeded in 0004 with full, production-grade legal copy.
--
-- The legal renderer (api/src/site-provisioning/legal-renderer.ts) PREFERS
-- legal_templates.content_html and only falls back to content_md; renderPageHtml
-- outputs content_html RAW (no markdown->HTML conversion). So we set content_html
-- to real HTML (h1/h2/p/ul/li/em) using ONLY the 6 SUPPORTED tokens
--   {{site_name}} {{domain}} {{contact_email}} {{privacy_email}}
--   {{effective_date}} {{company_name}}
-- (substituteLegalTemplate does NOT escape, so the HTML renders). Idempotent
-- UPDATE by unique slug. The Do-Not-Sell opt-out BUTTON is injected at render
-- time by renderPageHtml, not stored here.

UPDATE legal_templates SET content_html = '<h1>Privacy Policy</h1><p><em>Last updated: {{effective_date}}</em></p><p>This Privacy Policy explains how {{site_name}} collects, uses, and protects information when you visit {{domain}}.</p><h2>What we collect</h2><ul><li>Information you give us: if you subscribe to our newsletter or contact us, we collect your email address and any message you send.</li><li>Information collected automatically: basic analytics such as pages viewed, approximate region, device and browser type, and the site that referred you. This is aggregated and not used to identify you personally.</li><li>Cookies: a small number of cookies keep the site working, remember your preferences, and measure traffic. You can disable cookies in your browser settings.</li></ul><h2>How we use it</h2><p>We use this information to operate and improve {{site_name}}, send the newsletter you asked for, reply to your messages, and understand which content is useful. We do not sell your personal information for money. See the Do Not Sell or Share My Personal Information page for your choices.</p><h2>Advertising</h2><p>Some pages may show ads from third-party networks. Those partners may use cookies to show relevant ads and measure performance. You can opt out of personalized advertising through your device settings or industry tools such as the Digital Advertising Alliance.</p><h2>Your rights</h2><p>Depending on where you live, you may have the right to access, correct, or delete the personal information we hold, and to opt out of its sale or sharing. To make a request, email {{privacy_email}}. We respond within the time the law requires.</p><h2>Data retention and security</h2><p>We keep personal information only as long as needed for the purposes above, then delete it, and we use reasonable measures to protect it.</p><h2>Changes</h2><p>We may update this policy. Material changes are posted here with a new last-updated date.</p><h2>Contact</h2><p>Questions about privacy? Email {{privacy_email}}.</p>' WHERE slug = 'privacy-policy';

UPDATE legal_templates SET content_html = '<h1>Terms of Use</h1><p><em>Last updated: {{effective_date}}</em></p><p>Welcome to {{site_name}} ({{domain}}). By using this site you agree to these terms.</p><h2>Using our content</h2><p>The articles, images, and other content on {{site_name}} are provided for general information and enjoyment. You may read and share links freely. Please do not republish, sell, or redistribute our content in bulk without permission.</p><h2>No professional advice</h2><p>Our content is general information, not professional advice. For decisions about your health, finances, legal situation, or family, please consult a qualified professional. {{site_name}} is not responsible for actions taken based on our content.</p><h2>Your conduct</h2><p>When you contact us or submit information, you agree not to send unlawful, abusive, or infringing material.</p><h2>Third-party links and ads</h2><p>We may link to other sites and show advertising. We are not responsible for the content or practices of third parties.</p><h2>Disclaimer and liability</h2><p>The site is provided as is, without warranties of any kind. To the fullest extent permitted by law, {{company_name}} is not liable for indirect or consequential damages arising from your use of the site.</p><h2>Changes</h2><p>We may update these terms. Continued use means you accept the current version.</p><h2>Contact</h2><p>Questions? See our Contact page.</p>' WHERE slug = 'terms';

UPDATE legal_templates SET content_html = '<h1>Do Not Sell or Share My Personal Information</h1><p>{{site_name}} does not sell your personal information for money. Some online advertising can still count as selling or sharing under laws such as the California Consumer Privacy Act, because advertising partners may use cookies to build a profile for personalized ads.</p><p>You can opt out below. When you opt out, we signal our advertising partners not to sell or share your information, and we store your choice in a cookie on this device.</p><h2>Your choice</h2><p>Use the button below to opt out, or to opt back in. Your preference applies to this browser and device. If you clear cookies or use another device, set it again.</p><h2>Other rights</h2><p>You can also email {{privacy_email}} to request access to, or deletion of, the personal information we hold about you.</p>' WHERE slug = 'do-not-sell';

UPDATE legal_templates SET content_html = '<h1>Contact Us</h1><p>We would love to hear from you. Whether you have a question, a correction, a story idea, or a partnership enquiry, here is how to reach {{site_name}}.</p><h2>Email</h2><p>The fastest way to reach us is by email at {{contact_email}}. We read every message and aim to reply within a few business days.</p><h2>Corrections</h2><p>Spotted something inaccurate? Email {{contact_email}} with the article title and the detail you think is wrong. We correct mistakes promptly.</p><h2>Editorial and partnerships</h2><p>For editorial suggestions, guest contributions, or advertising and partnership enquiries, email {{contact_email}} with a short summary.</p><h2>Follow us</h2><p>You can also find {{site_name}} on social media using the links in the footer.</p>' WHERE slug = 'contact';
