// T19 [E2]: real POST /api/admin/ai/image handler.
//
// Mirrors the T18 chat endpoint contract (501 no-key, 400 bad input, 502 on
// OpenAI failure, ai_generations receipt row around every call) and adds the
// image-specific persistence: the generated bytes are PUT to R2 under a
// unique per-generation storage_key and a media row is inserted with
// site_id + ai_generation_id. A 2xx response is returned ONLY after the
// media row exists — if the INSERT yields no row the endpoint fails the
// receipt and responds 500.

import type { Context } from "hono";
import type { Env } from "../env";
import { getImageModel } from "../ai/models";
import { createOpenAIClient } from "../ai/openai-client";
import {
  finishGenerationLogFailure,
  finishGenerationLogSuccess,
  startGenerationLog,
} from "../ai/generation-log";

interface ImageBody {
  prompt?: string;
  site_id?: string | null;
  size?: string;
  alt_text?: string;
}

const IMAGE_TASK = "admin-image";
const IMAGE_PROMPT_VERSION = "v1";

// JSON prompt bodies only — 64 KiB is generous for text and blocks
// accidental base64/image uploads to this endpoint.
export const IMAGE_BODY_LIMIT_BYTES = 64 * 1024;

function newRequestId(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `img_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
}

export async function handleAdminAiImage(c: Context<{ Bindings: Env }>) {
  if (!c.env.OPENAI_API_KEY) {
    return c.json({ error: "OPENAI_API_KEY is not configured" }, 501);
  }
  let body: ImageBody = {};
  try {
    body = await c.req.json<ImageBody>();
  } catch {
    return c.json({ error: "Invalid JSON body" }, 400);
  }
  const prompt = typeof body.prompt === "string" ? body.prompt.trim() : "";
  if (!prompt) return c.json({ error: "prompt is required" }, 400);
  const site_id =
    typeof body.site_id === "string" && body.site_id !== "" ? body.site_id : null;
  const size = typeof body.size === "string" && body.size !== "" ? body.size : undefined;

  let model: string;
  try {
    model = getImageModel(c.env);
  } catch (err) {
    return c.json(
      { error: err instanceof Error ? err.message : String(err) },
      500,
    );
  }

  // Receipt row: every image call gets a fresh ai_generations row keyed by a
  // per-request idempotency_key (interactive generation is never replayed).
  const ai_generation_id = newRequestId();
  const idempotency_key = `${IMAGE_TASK}:${ai_generation_id}`;
  await startGenerationLog(c.env, {
    id: ai_generation_id,
    site_id,
    task: IMAGE_TASK,
    model,
    prompt_version: IMAGE_PROMPT_VERSION,
    idempotency_key,
    provider: "openai",
    request_json: { prompt, size: size ?? null },
    target_type: null,
    target_id: null,
  });

  const client = createOpenAIClient(c.env);
  try {
    const result = await client.generateImage({ prompt, size });
    if ("skipped_no_api_key" in result && result.skipped_no_api_key) {
      // Unreachable (key presence checked above) but type-required; keep the
      // 501 contract rather than inventing a fake success.
      return c.json({ error: "OPENAI_API_KEY is not configured" }, 501);
    }

    // Unique storage key per generation: /media/* is served immutable with a
    // 1-year max-age (media/serve.ts), so admin generations must never
    // overwrite a previously served key.
    const safeSite = (site_id ?? "shared").replace(/[^A-Za-z0-9_-]+/g, "-");
    const storage_key = `ai/admin/${safeSite}/${ai_generation_id}.png`;
    await c.env.MEDIA.put(storage_key, result.bytes, {
      httpMetadata: { contentType: result.mime },
    });

    const alt_text =
      typeof body.alt_text === "string" && body.alt_text.trim() !== ""
        ? body.alt_text.trim()
        : prompt.slice(0, 200);
    const mediaRow = await c.env.DB.prepare(
      "INSERT INTO media (filename, storage_key, mime_type, size_bytes, alt_text, folder, site_id, ai_generation_id) " +
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id",
    )
      .bind(
        `ai-admin-${ai_generation_id}.png`,
        storage_key,
        result.mime,
        result.bytes.byteLength,
        alt_text,
        "ai/admin",
        site_id,
        ai_generation_id,
      )
      .first<{ id: number }>();

    if (!mediaRow) {
      // Never 2xx without the DB row — the media row IS the endpoint's
      // persistence contract.
      await finishGenerationLogFailure(c.env, {
        idempotency_key,
        error_message: "media INSERT returned no row",
      });
      return c.json({ error: "media row insert failed", ai_generation_id }, 500);
    }

    await finishGenerationLogSuccess(c.env, {
      idempotency_key,
      response_json: { model: result.model, size: size ?? "1024x1024" },
      parsed_json: {
        media_id: mediaRow.id,
        storage_key,
        mime: result.mime,
        size_bytes: result.bytes.byteLength,
      },
    });
    return c.json({
      ok: true,
      model: result.model,
      media_id: mediaRow.id,
      storage_key,
      image_url: `/media/${storage_key}`,
      ai_generation_id,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await finishGenerationLogFailure(c.env, {
      idempotency_key,
      error_message: message,
    });
    return c.json({ error: "AI image request failed", ai_generation_id }, 502);
  }
}
