// Admin AI Generation detail template.
// Renders the read-only detail view at /admin/ai-generations/:id with
// the full row from ai_generations: task, model, prompt_version,
// status, target_type/target_id, idempotency_key, request_json,
// response_json, parsed_json, error_message, created_at, updated_at.
//
// Used by:
//   - GET /admin/ai-generations/:id (HTML shell)
//   - Provisioning job detail "AI step output" link
//   - Article editor's "Generated by AI" badge (deep link via
//     data-ai-generation-id / ai_generation_id)

import { adminLayout } from "./layout";

export interface AiGenerationDetailEntry {
  id: string;
  site_id: string | null;
  task: string;
  provider: string;
  model: string;
  prompt_version: string;
  idempotency_key: string;
  status: string;
  target_type: string | null;
  target_id: string | null;
  request_json: string | null;
  response_json: string | null;
  parsed_json: string | null;
  error_message: string | null;
  created_at: number | string | null;
  updated_at: number | string | null;
}

export interface AiGenerationDetailBranding {
  userEmail?: string;
}

function escapeHtml(input: string | number | null | undefined): string {
  if (input === undefined || input === null) return "";
  return String(input)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderJsonBlock(label: string, raw: string | null): string {
  const body = raw === null || raw === undefined ? "" : raw;
  return `<div class="form-group">
  <label class="form-label">${escapeHtml(label)}</label>
  <pre class="code-block" data-key="${escapeHtml(label)}">${escapeHtml(body)}</pre>
</div>`;
}

function renderDetailCard(g: AiGenerationDetailEntry): string {
  const id = escapeHtml(g.id);
  const status = escapeHtml(g.status);
  // ai_generation_id is the canonical field name (mirrors articles.ai_generation_id
  // + pages.ai_generation_id). Surface it as data-key + visible row so DOM
  // consumers can deep-link from articles / provisioning jobs.
  return `<article class="card ai-generation-detail" data-ai-generation-id="${id}">
  <header class="card-header">
    <h2 class="card-title">AI generation <span data-key="ai_generation_id">${id}</span></h2>
    <span class="badge badge-${status}">${status}</span>
  </header>
  <dl class="detail-list">
    <dt>Task</dt><dd>${escapeHtml(g.task)}</dd>
    <dt>Provider</dt><dd>${escapeHtml(g.provider)}</dd>
    <dt>Model</dt><dd>${escapeHtml(g.model)}</dd>
    <dt>Prompt version</dt><dd>${escapeHtml(g.prompt_version)}</dd>
    <dt>Status</dt><dd>${status}</dd>
    <dt>Site</dt><dd>${escapeHtml(g.site_id ?? "")}</dd>
    <dt>Target type</dt><dd>${escapeHtml(g.target_type ?? "")}</dd>
    <dt>Target id</dt><dd>${escapeHtml(g.target_id ?? "")}</dd>
    <dt>Idempotency key</dt><dd>${escapeHtml(g.idempotency_key)}</dd>
    <dt>Created at</dt><dd>${escapeHtml(g.created_at ?? "")}</dd>
    <dt>Updated at</dt><dd>${escapeHtml(g.updated_at ?? "")}</dd>
    <dt>Error</dt><dd>${escapeHtml(g.error_message ?? "")}</dd>
  </dl>
  ${renderJsonBlock("request_json", g.request_json)}
  ${renderJsonBlock("response_json", g.response_json)}
  ${renderJsonBlock("parsed_json", g.parsed_json)}
  <div class="form-actions">
    <a class="btn btn-secondary" href="/admin/ai-generations">&larr; Back to list</a>
  </div>
</article>`;
}

export function aiGenerationDetailPage(
  generation: AiGenerationDetailEntry,
  branding: AiGenerationDetailBranding = {},
): string {
  const content = renderDetailCard(generation);
  return adminLayout({
    title: `AI Generation ${generation.id}`,
    activePath: "/admin/ai-generations",
    userEmail: branding.userEmail,
    content,
  });
}

export function aiGenerationNotFoundPage(
  id: string,
  branding: AiGenerationDetailBranding = {},
): string {
  const safeId = escapeHtml(id);
  const content = `<div class="card">
  <div class="card-header"><h2 class="card-title">AI generation not found</h2></div>
  <p>No record found for <code data-key="ai_generation_id">${safeId}</code>.</p>
  <div class="form-actions">
    <a class="btn btn-secondary" href="/admin/ai-generations">&larr; Back to list</a>
  </div>
</div>`;
  return adminLayout({
    title: "AI Generation not found",
    activePath: "/admin/ai-generations",
    userEmail: branding.userEmail,
    content,
  });
}
