export { adminLayout } from "./layout";
export { dashboardPage } from "./dashboard";
export { domainsPage } from "./domains";
export { articlesListPage, articleFormPage } from "./articles";
export { pagesListPage, pageFormPage } from "./pages";
export { categoriesListPage } from "./categories";
export { tagsListPage } from "./tags";
export { mediaListPage } from "./media";
export { settingsPage } from "./settings";
export { presetsListPage } from "./presets";
export { editorScripts } from "../../editor/editor-scripts";
