// AUTO-GENERATED by `npm run build:conversions-admin`.
// DO NOT EDIT. `npm run verify:conversions-admin` rebuilds and byte-diffs this manifest and all four assets.
// ES2020 ESM; minified; production bundles have no source maps.
// gzipBytes is intentionally null: a gzip length is a property of the compressor, not of the
// asset, and identical bytes measure differently on different zlib builds. Asset identity is
// sha256 + bytes + fileName. Gzip budgets are enforced live on every build.

export const ADMIN_ASSET_MANIFEST = {
  conversions: {
    js: {
      fileName: "conversions.440f18d941c77d8e.js",
      url: "/assets/admin/conversions/conversions.440f18d941c77d8e.js",
      contentType: "text/javascript; charset=utf-8",
      etag: "\"sha256-440f18d941c77d8e4574c5bf3494107b8d72f098c27b60a512d57a151ef831ac\"",
      sha256: "440f18d941c77d8e4574c5bf3494107b8d72f098c27b60a512d57a151ef831ac",
      bytes: 156338,
      gzipBytes: null,
    },
    css: {
      fileName: "conversions.c7d2cf4b7616d207.css",
      url: "/assets/admin/conversions/conversions.c7d2cf4b7616d207.css",
      contentType: "text/css; charset=utf-8",
      etag: "\"sha256-c7d2cf4b7616d2078d79c845af005f6f1bd15d0f8441b19449b65c04ed131af7\"",
      sha256: "c7d2cf4b7616d2078d79c845af005f6f1bd15d0f8441b19449b65c04ed131af7",
      bytes: 22095,
      gzipBytes: null,
    },
  },
  reporting: {
    js: {
      fileName: "reporting.6c7f5bf63785d17e.js",
      url: "/assets/admin/reporting/reporting.6c7f5bf63785d17e.js",
      contentType: "text/javascript; charset=utf-8",
      etag: "\"sha256-6c7f5bf63785d17e47d1e1b2c2492b46c56a62c088fa30b67cc5d72343c3cac6\"",
      sha256: "6c7f5bf63785d17e47d1e1b2c2492b46c56a62c088fa30b67cc5d72343c3cac6",
      bytes: 87563,
      gzipBytes: null,
    },
    css: {
      fileName: "reporting.c7d2cf4b7616d207.css",
      url: "/assets/admin/reporting/reporting.c7d2cf4b7616d207.css",
      contentType: "text/css; charset=utf-8",
      etag: "\"sha256-c7d2cf4b7616d2078d79c845af005f6f1bd15d0f8441b19449b65c04ed131af7\"",
      sha256: "c7d2cf4b7616d2078d79c845af005f6f1bd15d0f8441b19449b65c04ed131af7",
      bytes: 22095,
      gzipBytes: null,
    },
  },
} as const;
