#!/usr/bin/env tsx
/**
 * build:leadgen-runtime — fix-contract v2.4 03 §3.2.
 *
 * esbuilds the LeadGen hydration runtime (entry
 * src/public/leadgen/runtime/engine.ts) into a single IIFE — target es2019,
 * minified, bundled, ZERO runtime dependencies — and emits it as a COMMITTED
 * TypeScript module:
 *
 *   src/public/leadgen/runtime/engine-bundle.generated.ts
 *     export const LEADGEN_RUNTIME_JS = "<the bundle>";
 *     export const LEADGEN_RUNTIME_JS_BYTES = <n>;
 *
 * The worker serves LEADGEN_RUNTIME_JS at GET /lg/runtime/{version}.js
 * (runtime-routes.ts) — committing the artifact keeps the deploy pipeline
 * free of a browser build step while `verify:leadgen-runtime` (CI gate)
 * rebuilds + byte-diffs it so it can never go stale, and asserts the §3.1
 * size budget (≤ 44032 bytes minified — the §3.1 "≤40KB" ceiling raised to
 * 42 KiB by operator decision D4 (2026-07-16), then to 43 KiB by Round-4
 * decision D-1 (2026-07-19) to fund AND/OR condition groups + the CTA/ctx
 * conditional-display data sources).
 *
 * DETERMINISM: no timestamps, no randomness, `charset: "ascii"` (pure-ASCII
 * output, asserted below), pinned esbuild (0.28.1 devDependency) — the same
 * sources always produce byte-identical output, so the verify diff is exact.
 */
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const API_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const RUNTIME_ENTRY = resolve(API_ROOT, "src/public/leadgen/runtime/engine.ts");
export const GENERATED_PATH = resolve(
  API_ROOT,
  "src/public/leadgen/runtime/engine-bundle.generated.ts",
);
// §3.1 "≤40KB minified", raised to 42 KiB by D4 (2026-07-16), then to 43 KiB
// (44032) by Round-4 decision D-1 (2026-07-19).
export const MAX_BUNDLE_BYTES = 44032;

export interface RuntimeBundle {
  js: string;
  bytes: number;
  moduleSource: string;
}

export async function buildRuntimeBundle(): Promise<RuntimeBundle> {
  const result = await build({
    entryPoints: [RUNTIME_ENTRY],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2019",
    minify: true,
    charset: "ascii",
    legalComments: "none",
    write: false,
    logLevel: "silent",
  });
  const out = result.outputFiles[0];
  if (out === undefined) throw new Error("esbuild produced no output");
  const js = out.text;
  // Determinism guard: ascii charset means byte length === string length and
  // the emitted literal below needs no non-ASCII escaping edge cases.
  if (!/^[\x00-\x7F]*$/.test(js)) {
    throw new Error("bundle contains non-ASCII bytes despite charset:ascii");
  }
  const bytes = Buffer.byteLength(js, "utf8");
  const moduleSource =
    "// AUTO-GENERATED by `npm run build:leadgen-runtime`" +
    " (scripts/build-leadgen-runtime.ts).\n" +
    "// DO NOT EDIT — `npm run verify:leadgen-runtime` rebuilds and byte-diffs this file\n" +
    "// (stale = CI failure) and gates LEADGEN_RUNTIME_JS_BYTES <= 44032 (03 SS3.1/SS3.2, D4/D-1).\n" +
    "//\n" +
    "// Source: src/public/leadgen/runtime/engine.ts (+ its runtime/* imports),\n" +
    "// bundled as a minified es2019 IIFE, ascii-only, zero dependencies.\n" +
    "// Served by GET /lg/runtime/{LEADGEN_TEMPLATE_VERSION}.js (runtime-routes.ts).\n" +
    "\n" +
    `export const LEADGEN_RUNTIME_JS = ${JSON.stringify(js)};\n` +
    "\n" +
    `export const LEADGEN_RUNTIME_JS_BYTES = ${bytes};\n`;
  return { js, bytes, moduleSource };
}

export function readCommittedBundleSource(): string | null {
  try {
    return readFileSync(GENERATED_PATH, "utf8");
  } catch {
    return null;
  }
}

async function main(): Promise<void> {
  const bundle = await buildRuntimeBundle();
  writeFileSync(GENERATED_PATH, bundle.moduleSource, "utf8");
  const pct = ((bundle.bytes / MAX_BUNDLE_BYTES) * 100).toFixed(1);
  console.log(
    `build:leadgen-runtime → ${GENERATED_PATH}\n` +
      `  bundle: ${bundle.bytes} bytes (${pct}% of the ${MAX_BUNDLE_BYTES}-byte budget)`,
  );
  if (bundle.bytes > MAX_BUNDLE_BYTES) {
    console.error(
      `  WARNING: bundle exceeds the §3.1 budget — verify:leadgen-runtime WILL fail.`,
    );
    process.exitCode = 1;
  }
}

const invokedDirectly = (() => {
  try {
    const self = fileURLToPath(import.meta.url);
    const invoked = process.argv[1] !== undefined ? resolve(process.argv[1]) : "";
    return self === invoked;
  } catch {
    return false;
  }
})();

if (invokedDirectly) {
  main().catch((err) => {
    console.error(`build:leadgen-runtime failed: ${err instanceof Error ? err.message : err}`);
    process.exit(1);
  });
}
